### ISSUE TITLE
just to mention

### ISSUE THREAD

**Issue by teto** [haorenW1025/diagnostic-nvim#1]
just  wanted to mention that these 2 items have been merged on neovim master already see https://github.com/neovim/neovim/pull/11668:
- Option to change sign text.
- Support different signs for different diagnosis level.

**Comment by haorenW1025** [comment]
Wow that's amazing!
I'm just creating this plugins to let it be a wrapper of the built-in LSP so if the features is already built-in, maybe I'll add an option to disable it for different filetype.
thanks for the mention!
