### ISSUE TITLE
feature request: add wrap commands

### ISSUE THREAD

**Issue by ruifm** [haorenW1025/diagnostic-nvim#11]
Everything works great but when comparing with [ale](https://github.com/dense-analysis/ale), I'm missing at least 2 commands:

```vim
:PrevWrapDiagnostic
:NextWrapDiagnostic
```

These variants would wrap arround a buffer, making warning navigation more seamless.

Another *nice-to-have* that maybe it's outside the scope of this plugin would be `OpenDiagnosticToggle` so that it would be easier to open-close the quickfix diagnostics window without needing to navigate to it and close it manually.

**Comment by haorenW1025** [comment]
Actually similar functionality has been implemented in #8 . You can use `:NextDiagnosticCycle` and `:PrevDiagnosticCycle` to do the work(should've documented that in README though).
I can implement the `openDiagonsticToggle` command though.

**Comment by ruifm** [comment]
Thanks a lot! Somehow I missed that PR.

I've been thinking about the `:OpenDiagnosticToggle` and maybe since it's something specific to the quickfix window which has broader applications than a diagnostics window, maybe it should be outside the scope of this plugin. I merely suggested it for consistency.

I personally use [romainl's vim-qf](https://github.com/romainl/vim-qf) to manage my quickfix window so that feature is not an absolute necessity.

I will close this issue if you see it likewise.

**Comment by haorenW1025** [comment]
Hmm I think you're right. Since the diagnostic list only use the built-in location list handling it should be out of the scope of this plugins.
