### ISSUE TITLE
Hints are not displayed

### ISSUE THREAD

**Issue by gbrlsnchs** [haorenW1025/diagnostic-nvim#13]
After activating this plugin, I stopped seeing hints in my JavaScript code, only errors (and possibly warnings).

It would be nice if this plugin still showed everything the default diagnostics showed, like errors, warnings, hints and information.

**Comment by haorenW1025** [comment]
Actually there is a option which you can set up the lowest diagnostic level like this
```vim
let g:diagnostic_level = 'Hint'
```
Sorry for not documented that very well though, and I should change the default value of this to be `Hint` instead of `Warning`.

**Comment by gbrlsnchs** [comment]
Awesome, @haorenW1025. No problem for the lack of documentation, I believe that's part of this plugin's early stage. I could've searched in the source code but time's short right now.
