### ISSUE TITLE
Hide ellipsis when g:diagnostic_trimmed_virtual_text is zero

### ISSUE THREAD

**Issue by gbrlsnchs** [haorenW1025/diagnostic-nvim#17]
This is just my opinion, so feel free to close it if you don't agree. I think when `g:diagnostic_trimmed_virtual_text` equals `0`, the ellipsis should be hidden and only the symbols should be shown. Without any text the ellipsis doesn't have any value, since we already know there are error messages only by seeing the error symbols.

**Comment by haorenW1025** [comment]
You're right. It should be fixed in the latest commit, please update and check!

**Comment by gbrlsnchs** [comment]
Great job! Working as intended. Thanks for your dedication! :tada:
