### ISSUE TITLE
Regression: custom signs no longer work

### ISSUE THREAD

**Issue by gbrlsnchs** [haorenW1025/diagnostic-nvim#19]
It seems commit f88b35a5808c6e3817b5d7059f2c1857ade296b3 has introduced a bug which disables setting custom diagnostic symbols. I checked out every commit between my last version and the regression, and that commit is the culprit.

**Comment by haorenW1025** [comment]
If you means the sign of the diagnostic, that's because I've followed the master branch and they don't use global variables to set up anymore. Instead you can use
```vim
call sign_define("LspDiagnosticsErrorSign", {"text" : " ", "texthl" : "LspDiagnosticsError"})
call sign_define("LspDiagnosticsWarningSign", {"text" : "⚡", "texthl" : "LspDiagnosticsWarning"})
```
see `:h vim.lsp.util.buf_diagnostics_signs()`, there's a document of how it works(but maybe require a newer branch).

**Comment by ckipp01** [comment]
Ahh, I commented [here](https://github.com/haorenW1025/diagnostic-nvim/commit/f88b35a5808c6e3817b5d7059f2c1857ade296b3#r39166284) before seeing this issue. Didn't know they changed this. I'll change this locally.

**Comment by ckipp01** [comment]
Related to the above, do you have any idea how to give this priority over GitGutter signs?

**Comment by haorenW1025** [comment]
@ckipp01 I think you can't give priority through built-in method. I can create an option and enable it in `diagnostic-nvim` though.

**Comment by ckipp01** [comment]
That's sort of a bummer. I think it'd be a good idea to enable that then. If not, I'm assuming users that use GitGutter are going to be confused why their custom signs aren't showing.

**Comment by haorenW1025** [comment]
I've added an option to customize sign priority. It's already bigger than gitgutter by default so you should see the fix once you update.

**Comment by ckipp01** [comment]
That was fast 😆 .

Yes, it works perfectly. 🙏

**Comment by gbrlsnchs** [comment]
@haorenW1025 That's it, then, thank you for your attention again! And, yes, sorry, I meant signs, not symbols. :grimacing:
