### ISSUE TITLE
NextDiagnostic won't work if an error is at the end of the row

### ISSUE THREAD

**Issue by Weypare** [haorenW1025/diagnostic-nvim#2]
**Minimal example:**
```c
int main() {
  int a = 0
  int b = 0;

  return 0
}
```
This produces 2 diagnostics of missing semicolon:
```
test.c|2 col 12| int a = 0
test.c|5 col 11| return 0
```
**Expected behavior:**
```
:NextDiagnostic<CR>
:NextDiagnostic<CR>
```
will put the cursor at the end of return statement.

**Actual behavior:**
The cursor stays at the end of the second row.

**Comment by haorenW1025** [comment]
Sorry for the late replied, but after I check this, it's actually because C/C++ language server will mark the diagnostics at column 12 in your example, but column 12 doesn't have any text available..., maybe I'll do a workaround to handle this case but I'll need to test it first.

**Comment by haorenW1025** [comment]
should be fixed, please update and check, thanks

**Comment by Weypare** [comment]
Checked, everything works fine
