### ISSUE TITLE
not working with gopls and rust_analyzer

### ISSUE THREAD

**Issue by ataul443** [haorenW1025/diagnostic-nvim#23]
I was really excited to try this out in my nvim. Unfortunately it is not working. It is not showing any kind of diagnostic at all with gopls and rust_analyzer

NVIM --
```
NVIM v0.5.0-521-gc6dc39780
Build type: Debug
LuaJIT 2.1.0-beta3
```

inti.vim ---
```
call plug#begin(expand('~/.config/nvim/plugged'))
Plug 'neovim/nvim-lsp'
Plug 'haorenW1025/diagnostic-nvim'
call plug#end()

lua require'nvim_lsp'.gopls.setup{on_attach=require'diagnostic'.on_attach}
lua require'nvim_lsp'.rust_analyzer.setup{on_attach=require'diagnostic'.on_attach}
```

**Comment by ataul443** [comment]
However, your completion-nvim plugin working totally awesome.

**Comment by haorenW1025** [comment]
Hmm it seems working on my side with rust-analyzer...
<img width="506" alt="Screen Shot 2020-05-26 at 1 12 38 AM" src="https://user-images.githubusercontent.com/35623968/82832552-fef30a80-9eed-11ea-8d91-c5caf0f3d91d.png">

**Comment by ataul443** [comment]
Sorry, my bad, got it working. having issue with the config itself.
