### ISSUE TITLE
Way to automatically show diagnostic info floating window on cursor hover

### ISSUE THREAD

**Issue by pyrr** [haorenW1025/diagnostic-nvim#24]
Is there a way to currently do this, similarly to how it happens in the demo but without pressing anything ?

**Comment by haorenW1025** [comment]
You actually don't need diagnostic_nvim for this. Use a autocmd with the built-in command like this
```vim
autocmd CursorHold * lua vim.lsp.util.show_line_diagnostics()
```

**Comment by pyrr** [comment]
Will this play nice with let g:diagnostic_insert_delay = 1 ?

**Comment by haorenW1025** [comment]
It should be fine. You can try it:)
