### ISSUE TITLE
Auto pop up does not work

### ISSUE THREAD

**Issue by kdheepak** [haorenW1025/diagnostic-nvim#25]
Thanks for making this plugin!

I have the following in my `.vimrc`:

```vim
let g:diagnostic_auto_popup_while_jump = 1
let g:diagnostic_enable_virtual_text = 0
```

When I hover over this line, I get the following:

![Screen Shot 2020-05-26 at 4 04 53 PM](https://user-images.githubusercontent.com/1813121/82954776-a6ae1e00-9f6a-11ea-95fd-6020d9554fd8.png)

This shows the error in the gutter but doesn't show the pop up with the diagnostics.

If I call `:lua vim.lsp.util.show_line_diagnostics()<CR>` I get the following:

![Screen Shot 2020-05-26 at 4 05 22 PM](https://user-images.githubusercontent.com/1813121/82954890-e07f2480-9f6a-11ea-859e-8ae523f5f55f.png)

Do you happen to know what might be going on?

**Comment by haorenW1025** [comment]
Auto pop up only works when using `:NextDiagnostic` or `:PrevDiagnostic` to jump between location list. If you want it to automatically pop up, use this autocmd
```vim
autocmd CursorHold * lua vim.lsp.util.show_line_diagnostics()
```

**Comment by kdheepak** [comment]
Nice! Thank you so much for the fast reply!
