### ISSUE TITLE
Incorrect virtual text display for some diagnostics

### ISSUE THREAD

**Issue by dutchgecko** [haorenW1025/diagnostic-nvim#27]
![image](https://user-images.githubusercontent.com/2513484/83443070-6f97ab00-a449-11ea-96fd-6703f35e0423.png)

Sample screenshot from a piece of lua (and a language server which isn't fully set up yet, ahem).

As you can see, the multiple warnings that `vim` is not defined seem to work as expected, but the warning for the unused function is using incorrect highlighting and a doubled up `diagnostic_virtual_text_prefix`.

Possible reasons that I could think of are:

1. There are two errors on this line, see next screenshot:
![image](https://user-images.githubusercontent.com/2513484/83443308-cf8e5180-a449-11ea-9d6f-253ef81b6cfd.png)

    * Note: the highlighting in the Hover popup here is also incorrect, since the highlighting for popups on later lines matches the virtual text: 

    ![image](https://user-images.githubusercontent.com/2513484/83443757-8f7b9e80-a44a-11ea-8b4c-669490dab171.png)

1. The highlighting for diagnostic type "Hint" is different to type "Warning".

Settings from init.vim (screenshotted to include NerdFont glyphs)

![image](https://user-images.githubusercontent.com/2513484/83443535-314ebb80-a44a-11ea-8f25-aba018e5c5bf.png)

**Comment by dutchgecko** [comment]
Already managed to get some better reproducers. It seems that the double text_prefix is caused by having two warnings on a line, and the incorrect highlighting is caused by the Hint type. Screenshots (same code but edited variable name):

![image](https://user-images.githubusercontent.com/2513484/83445185-d1a5df80-a44c-11ea-8c26-66d1864ca4fa.png)

![image](https://user-images.githubusercontent.com/2513484/83445202-d9658400-a44c-11ea-848f-217897c3934c.png)

**Comment by haorenW1025** [comment]
Actually the multiple prefix seems to be the default behavior. If you disable `diagnostic-nvim` and use the same lsp you'll notice the same behavior. You should open up an issue in neovim's repo if you're confused by it. Can you also try if you can reproduce the incorrect highlight issue without `diagnostic-nvim`?

**Comment by dutchgecko** [comment]
Hi, you're quite right, both are occurring without the use of `diagnostic-nvim`.

The highlighting seems to be a missing HL group in my colorscheme. I'll ask at neovim what's up with the repeated virtual text prefix.
