### ISSUE TITLE
no diagnostic at all

### ISSUE THREAD

**Issue by cinghiopinghio** [haorenW1025/diagnostic-nvim#3]
This is an exiting time for neovim with builtin lsp, treesitter coming soon.
Thanks for this project.

Unfortunately, while the completion plugin is working out of the box, this one is not.
With this [init.nvim](https://gist.github.com/cinghiopinghio/8a2b44a86b768d2f6c04565bfc93d05a) I can see no floating windows with diagnostics. Not even with the following code full of mistakes:
``` python
import thiisnot as np
import numba as nb


de pipppp(suppp):
pass
```

I'm using last `nightly`, and last commits from your project.

**Comment by haorenW1025** [comment]
First of all, you cannot set the on_attach function twice as in your init.vim. You should use a wrapper function for that. Create a file `~/.config/nvim/lua/on_attach.lua` and put this in
```.lua
local M = {}
M.on_attach = function()
  require'diagnostic'.on_attach()
  require'completion'.on_attach()
end
return M
```
And use this in your init.vim
```.vim
lua require'nvim_lsp'.pyls.setup{on_attach=require'on_attach'.on_attach}
```
Sorry for the inconvenient for now though, actually I never think that I'll create completion-nvim so I wrote this. Completion-nvim is now geared toward a more general purpose completion framework and probably will not use the on_attach setup in the near future.

About the no diagnostic things, actually diagnostic-nvim will not take care of the diagnostic message, it just create some wrapper to make it easier to config. So if the code has no diagnostic at all I think it might be a language-server specific issue.  Could you try pyls_ms instead and see if it works? It should work better in my experience.

**Comment by cinghiopinghio** [comment]
Thanks for the hints.

1. I removed the double `on_attach`.
2. It seems to work  with `pyls_ms` but not with `pyls` so it might be a problem on their side.

**Comment by haorenW1025** [comment]
OK, closing this for now, feel free to reopen if any issue happen!
