### ISSUE TITLE
Diagnostic when buffer doesn't exist

### ISSUE THREAD

**Issue by Shatur95** [haorenW1025/diagnostic-nvim#31]
I see that last two commits (8226360c804c919234fd37ab9d1df3866e3c9058 and 6adf7ee518288c5aa874af91b78cf9b3f7ead4c9) fixes diagnostics for unloaded buffers.
But it looks like this has already been fixed on the neovim side: https://github.com/neovim/neovim/commit/dd4018947c9f9b39b4e473c21ebf0e27f1e7ddc5
Is this is fixes for different things?

**Comment by Wraul** [comment]
I have a suspicion that 8226360c804c919234fd37ab9d1df3866e3c9058 also broke the location list.

**Comment by haorenW1025** [comment]
@Wraul you're right. I've noticed it on my side. I reverted the changes back.
@Shatur95 I think the fix is for different things. I'm trying to fix the diagnostic for files that aren't exist(created by `:vsplit` or others).

**Comment by Shatur95** [comment]
Okay, thanks :)
