### ISSUE TITLE
`diagnostic-nvim` changes the statusline when using `lightline.vim`

### ISSUE THREAD

**Issue by kdheepak** [haorenW1025/diagnostic-nvim#32]
Thank you for writing this plugin! It works great!

I have a .vimrc file below:

```
call plug#begin('~/.local/share/nvim/plugged')
Plug '~/gitrepos/nvim-lsp'
Plug 'haorenW1025/diagnostic-nvim'          " better diagnostic
Plug 'itchyny/lightline.vim' 				" status bar
Plug 'JuliaEditorSupport/julia-vim'
Plug '~/gitrepos/vim-one'
call plug#end()

set shortmess+=c
set shortmess+=I
set completeopt=menuone,noinsert,noselect
set laststatus=2
set noshowmode

colorscheme one
set background=light

let g:diagnostic_show_sign = 0

lua << EOF
  local nvim_lsp = require'nvim_lsp'
  local on_attach = function(_, bufnr)
    vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
    require'diagnostic'.on_attach()
  end

  nvim_lsp.julials.setup{
    on_attach=on_attach;
  }
EOF

```

If `require'diagnostic'.on_attach()` is commented, everything works as expected.

However, if `require'diagnostic'.on_attach()` is not commented, then when LanguageServer.jl sends `textDocument/publishDiagnostics`, the status line changes.

Before `textDocument/publishDiagnostics`:

![](https://user-images.githubusercontent.com/1813121/84393631-0fc3a180-abb9-11ea-8b1e-89c7ddb02a76.png)

After `textDocument/publishDiagnostics`:

![](https://user-images.githubusercontent.com/1813121/84393699-210cae00-abb9-11ea-9581-301fce9ba6fe.png)

I looked through the package and I don't see why using this package would have any effect on the statusline. I wanted to check if you have any idea what might be going on? This seems to only be an issue when using `lightline.vim` and `diagnostic-nvim`. I'm not having this issue if I use `airline.vim` and `diagnostic-nvim`.

**Comment by haorenW1025** [comment]
That's quite weird... I haven't use `lightline.vim` for a while though. I'll look into that.

**Comment by kdheepak** [comment]
Thanks for the really quick response! Let me know if I can provide any more information.

**Comment by haorenW1025** [comment]
Have you tried with different lsp and see if it can be reproduce? I've tried rust-analyer and vimls and it works fine on my side.

**Comment by kdheepak** [comment]
I'll try with some other LSP as well and get back to you!

**Comment by kdheepak** [comment]
Hmm. I've tried it with a few environments, but I'm not able to replicate it. I've even tried it with a different Julia environment and it doesn't always do this. But there's a couple of environments where I can consistently replicate this issue. 

Any suggestions on how to debug this?

**Comment by kdheepak** [comment]
It's probably not an issue with this package, so I think we can close it here. I'll open a issue on the `lightline.vim` repo.

**Comment by kdheepak** [comment]
Well I think it's this issue actually: https://github.com/itchyny/lightline.vim/issues/448
