### ISSUE TITLE
option to disable all passive lint highlighting

### ISSUE THREAD

**Issue by ExpandingMan** [haorenW1025/diagnostic-nvim#33]
I've been banging my head against the wall for quite a while now trying to disable *ONLY* the passive text highlighting.

![2020-06-11-103100_465x106_scrot](https://user-images.githubusercontent.com/11379353/84399249-b5cdd680-abce-11ea-8886-cbf6502ef077.png)

Like in this example, I don't want *any* of these highlights and underlines, but I do want the pop-ups to work when I ask for them with proper highlighting.

![2020-06-11-103227_491x76_scrot](https://user-images.githubusercontent.com/11379353/84399437-db5ae000-abce-11ea-8216-2464fe72640a.png)
(e.g. I *do* want the above, only in the pop-up).

For the life of me I can't seem to get this to happen with `neovim-lsp`.  The closest I can get is turning off all LSP-related highlighting by setting, e.g.
```vim
hi! LspDiagnosticsUnderline ctermbg=none
hi! LspDiagnosticsInformation ctermbg=none
hi! LspDiagnosticsHint ctermbg=none
hi! LspDiagnosticsError ctermbg=none
hi! LspDiagnosticsWarning ctermbg=none
hi! LspDiagnosticsUnderlineError ctermbg=none
hi! LspDiagnosticsUnderlineHint ctermbg=none
hi! LspDiagnosticsUnderlineInformation ctermbg=none
hi! LspDiagnosticsUnderlineWarning ctermbg=none
```
but this *also* turns off just about every form of highlighting in the pop-ups, which is not what I want.

Any idea if there's any way of doing this?  Can an option be added in this package?

**Comment by haorenW1025** [comment]
I can try to add that:)

**Comment by haorenW1025** [comment]
Can you try adding this?
```vim
    let g:diagnostic_enable_underline = 0
```

**Comment by ExpandingMan** [comment]
It **WORKS!!!**.  Yay, thanks *so* much for your help here, that was absolutely driving me completely bananas.  Seemed like something so simple that I absolutely just could not get it to do.

Note that I have not yet thoroughly tested that it works for *everything*, so if I find something fishy I'll post another issue.  Thanks again!
