### ISSUE TITLE
diagnostic appears as message before being displayed as a popup

### ISSUE THREAD

**Issue by teto** [haorenW1025/diagnostic-nvim#4]
There is a strange issue when I use successive Prev/NextDiagnostic. Sometimes the diagnostic is displayed next to the statusline right before being displayed as a popup, see the bottom of the screenshot:

![2020-03-28-173343_636x719_scrot](https://user-images.githubusercontent.com/886074/77828054-ac79b580-7119-11ea-9178-afd1ed4f4e87.png)

Maybe it's something in my config but I am not sure what.

**Comment by haorenW1025** [comment]
The message is from location list because I use location list to jump around. I've changed it to run silently. It should be fixed now, please update and check!

**Comment by teto** [comment]
that seems to have fixed it thanks !
