### ISSUE TITLE
Use with completion-nvim

### ISSUE THREAD

**Issue by mhartington** [haorenW1025/diagnostic-nvim#7]
👋 hello. I found this plugin as well as completion-nvim 

https://github.com/haorenW1025/completion-nvim

Since both plugins  require setup using `on_attach`, how would one go about using both plugins?

**Comment by carlitux** [comment]
@mhartington take a look this https://github.com/haorenW1025/completion-nvim/issues/17

**Comment by mhartington** [comment]
Thank you!
